"""create data_types table

Revision ID: f79c10ba5af1
Revises: 
Create Date: 2025-10-14 09:46:49.358429+00:00

"""
from typing import Sequence, Union 
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79c10ba5af1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(), nullable=True, server_default=sa.text('NOW()')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_types_pkey'))
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_types')
    # ### end Alembic commands ###
